title: The Compassionate Programmer
subtitle: a student's guide to building software in teams
url: https://gvwilson.github.io/bst
repository: gvwilson/bst

chapters:
  - slug: "introduction"
    title: "Introduction"
  - slug: "important-stuff"
    title: "The Important Stuff"
  - slug: "getting-started"
    title: "Getting Started"
  - slug: "teams"
    title: "Teams"
  - slug: "version-control"
    title: "Version Control and All That"
  - slug: "software-forge"
    title: "What Else Your Software Forge Can Do For You"
  - slug: "test-debug"
    title: "Testing and Debugging"
  - slug: "tooling"
    title: "Tooling"
  - slug: "process"
    title: "Process"
  - slug: "design"
    title: "Design"
  - slug: "thinking-learning"
    title: "Thinking and Learning"
  - slug: "legalities"
    title: "Legalities"
  - slug: "wrapping-up"
    title: "Wrapping Up"
  - slug: "conclusion"
    title: "Conclusion"
  - appendix: true
  - slug: "license"
    title: "Licensing"
    file: "LICENSE.md"
  - slug: "bibliography"
    title: "Bibliography"
  - slug: "conduct"
    title: "Code of Conduct"
    file: "CONDUCT.md"
  - slug: "contributing"
    title: "Contributing"
    file: "CONTRIBUTING.md"
  - slug: "glossary"
    title: "Glossary"
  - slug: "performance-evaluation"
    title: "Performance Evaluation"

author:
  name: Greg Wilson
  url: third-bit.com
  email: gvwilson@third-bit.com
  github: https://github.com/gvwilson
  twitter: https://twitter.com/gvwilson
  linkedin: https://www.linkedin.com/in/greg-wilson-a26510b6/

markdown: kramdown

kramdown:
    syntax_highlighter_opts:
      disable: true

exclude:
  - '*.sublime-*'
  - README.md
  - Gemfile
  - Gemfile.lock
  - Makefile
  - vendor/bundle
  - book.*

permalink: pretty

blog:
  truncated_preview: false

sass:
  sass_dir: _sass
  style: :compressed

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist
