title: Building Software Together
subtitle: a student's guide to team software projects
url: https://gvwilson.github.io/bst
repository: gvwilson/bst

chapters:
  - slug: "introduction"
    title: "Introduction"
  - slug: "important-stuff"
    title: "The Important Stuff"
  - slug: "getting-rolling"
    title: "Getting Rolling"
  - slug: "teams"
    title: "Teams"
  - slug: "tooling"
    title: "Tooling"
  - slug: "process"
    title: "Process"
  - slug: "design"
    title: "Design"
  - slug: "legalities"
    title: "Legalities"
  - slug: "wrapping-up"
    title: "Wrapping Up"
  - appendix: true
  - slug: "license"
    title: "Licensing"
  - slug: "bibliography"
    title: "Bibliography"
  - slug: "glossary"
    title: "Glossary"
  - slug: "performance-evaluation"
    title: "Performance Evaluation"

author:
  name: Greg Wilson
  url: third-bit.com
  email: gvwilson@third-bit.com
  github: https://github.com/gvwilson
  twitter: https://twitter.com/gvwilson
  linkedin: https://www.linkedin.com/in/greg-wilson-a26510b6/

markdown: kramdown
highlighter: rouge

exclude:
  - '*.sublime-*'
  - README.md
  - Gemfile
  - Gemfile.lock
  - Makefile
  - vendor/bundle

permalink: pretty

blog:
  truncated_preview: false

sass:
  sass_dir: _sass
  style: :compressed

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist
